<?php
  /**
  * Implements hook_menu().
  */
  
  function pruebaformulario_menu() {
    $items['nire/form1'] = array(
	  'title' => t('Example Form 1'),
	  'page callback' => 'drupal_get_form',
	  'page arguments' => array('forms_nireneko_form1'),
	  'access callback' => TRUE,
	  'description' => t('Example Form 1'),
	  'type' => MENU_CALLBACK,
	);
	return $items;
  }
  
  /**
  * Function de retorno para la pagina nire/form1.
  */
  
  function forms_nireneko_form1($form_state) {
    $form['description'] = array(
	  '#type' => 'item',
	  '#title' => t('A simple form'),
	);
	
	$form['full_name'] = array(
	  '#type' => 'textfield',
	  '#title' => t('Full name'),
	  '#maxlength' => '10',
	);
	$form['password'] = array(
	  '#type' => 'password',
	  '#title' => t('Password'),
	);
	$form['email'] = array(
	  '#type' => 'textfield',
	  '#title' => t('Email'),
	);
	$form['city'] = array(
	  '#type' => 'textfield',
	  '#title' => t('City'),
	);
	
	$form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Enviar',
    );
	return $form;
  }
?>