<?php
function blocks_rbcode_block_info(){
  $blocks['unplubished_block'] = array(
    'info' => t('Bloque no publicado'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

function blocks_rbcode_block_configure($delta = ''){
  $form = array();

  switch($delta){
    case 'unplubished_block':
      $form['num_nodes'] = array(
        '#type' => 'select',
        '#title' => t('Selecciona la cantidad de nodos a mostrar en el bloque'),
        '#default_value' => variable_get('blocks_rbcode_num_nodes',3),
        '#options' => array(1=>1, 2=>2, 3=>3, 4=>4, 5=>5),
      );
      break;
  }
  return $form;
}
?>